FROM python:3.10.0

WORKDIR /app

COPY dependencies.txt /app/

RUN pip install --no-cache-dir --upgrade pip==24.2

RUN pip install --no-cache-dir -r dependencies.txt

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY . /app

CMD ["python","app.py"]